name: Benchmarks

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt install gcc-12 g++-12 rustc hyperfine
        # remove old symlinks
        sudo rm /usr/bin/gcc
        sudo rm /usr/bin/g++
        # create new symlinks
        sudo ln -s /usr/bin/gcc-12 /usr/bin/gcc
        sudo ln -s /usr/bin/g++-12 /usr/bin/g++

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.7"

    - name: Build project
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc) wisnia
        sudo cp src/wisnia /usr/bin

    - name: Run "29988-lines-of-code" benchmark
      run: |
        cd benchmarks/29988-lines-of-code
        python3.7 main.py --wisnia --cpp --rust 2000
        bash run.sh
