name: Ubuntu

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
        sudo apt install lcov
    - name: build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Coverage ..
        make -j$(nproc) wisnia wisnia-tests wisnia-coverage
    - name: collect code coverage
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -f build/wisnia-coverage.info
